### ISSUE TITLE
ARR animus books

### ISSUE THREAD

**Issue by Ashragnorok** [VarsityPhysicist/FFXIVRelicTracker#3]
I have been using this application to track my progress through the ARR relics. The Animus tab only has 8 of the 9 books available from the dropdown. It also seems like some of the book tasks have been mixed up.

Books Available (8/9)
Book of skyfire I
Book of skyfire II
Book of skyfall I
Book of skyfall II
Book of netherfire I
Book of netherfall I
Book of skywind I
Book of skyearth I

Books required for each weapon
Book of skyfire I
Book of skyfire II
Book of skyfall I
Book of skyfall II
Book of netherfire I
Book of netherfall I
Book of skywind I
**Book of skywind II** <- this book seems to be missing
Book of skyearth I

**Comment by VarsityPhysicist** [comment]
Hi Ashragnorok,

Thank you for pointing this out, I have published a new version that should address these issues

There were a couple problems causing the issues you found:

-I did have all the tasks for the 9 books programmed in, but I neglected to include the skywind II book, so all the skyearth I tasks should have been the skywind II tasks and the actual skyearth I could not be displayed

-I had the tasks programmed to update _before_ the selected book was updated, this was probably causing some mix ups...

-I've resolved a bug that the tasks displayed on the map would not update on the book selection changing

Thank you for reporting these issues, I'm going to mark this as closed because the 1.5 update should have resolved these issues, let me know if that is not correct

**Comment by Ashragnorok** [comment]
Thanks Varsity, I will test out the new version. Also, thank you for taking the time to develop this application. I have been working towards the relic weapons for all of the expansions, and this has been an amazing tool.
